# Site settings
title: Dilly Dally
tag_text: Dilly Dally 
description: A set of utilities that enables easy time logging and reporting on GitHub Issues
css-path: http://code.praqma.com/css/praqmacode.css

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["README.md"]
sass:
  style: compressed
